workflows:
  ios-unsigned-build:
    name: iOS Build (Unsigned for 3uTools)
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      vars:
        # Disabling stats speeds up pod install slightly
        COCOAPODS_DISABLE_STATS: true
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Clean and Get Packages
        script: |
          flutter clean
          flutter pub get

      - name: Install CocoaPods (Clean & Install)
        script: |
          cd ios
          
          # 1. Clear existing pod artifacts to force a fresh install
          rm -rf Pods
          rm -f Podfile.lock
          
          # 2. Install pods and update repo ONLY if needed (Faster than 'pod repo update')
          pod install --repo-update
          
          cd ..

      - name: Build iOS Release (No Code Signing)
        script: |
          # Build the .app bundle without signing
          # Note: This IPA will NOT install directly. It must be resigned by 3uTools/AltStore.
          flutter build ios --release --no-codesign --build-number=$BUILD_NUMBER

      - name: Create IPA from .app
        script: |
          cd build/ios/iphoneos
          
          # 1. Clean up previous artifacts
          rm -rf Payload *.ipa
          
          # 2. Create the Payload folder structure required by Apple
          mkdir Payload
          
          # 3. Copy the Runner.app into Payload
          cp -r Runner.app Payload/
          
          # 4. Zip the Payload folder into an .ipa file
          # We use underscores to avoid issues with spaces in filenames
          zip -r "My-Invois_e-Pos_Printer.ipa" Payload

    artifacts:
      - build/ios/iphoneos/*.ipa