workflows:
  ios-unsigned:
    name: iOS Unsigned IPA (For 3uTools)
    max_build_duration: 60
    instance_type: mac_mini_m1 # M1/M2 machines are faster, but standard mac_pro works too
    environment:
      flutter: stable
      xcode: latest # Uses the latest stable Xcode version
      cocoapods: default
    
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Install CocoaPods
        script: |
          find . -name "Podfile" -execdir pod install \;

      - name: Build iOS App (No Codesign)
        script: |
          # 1. Build the Release version, but explicitly tell Flutter/Xcode NOT to sign it
          flutter build ios --release --no-codesign

      - name: Package as IPA
        script: |
          # 2. Navigate to where the build artifact is
          cd build/ios/iphoneos
          
          # 3. Create the standard IPA folder structure
          # An IPA is just a zip file with a "Payload" folder containing the app
          mkdir Payload
          mv Runner.app Payload/
          
          # 4. Zip the Payload folder into an .ipa file
          # -r: recursive
          # -y: store symbolic links as the link instead of the referenced file (Crucial for iOS apps)
          zip -r -y app_unsigned.ipa Payload/
          
          # 5. Move the generated IPA to Codemagic's export directory
          mv app_unsigned.ipa $CM_EXPORT_DIR/runner_unsigned.ipa

    artifacts:
      - $CM_EXPORT_DIR/*.ipa
      - $CM_EXPORT_DIR/*.dSYM # Optional: Good for debugging crash reports later