workflows:
  ios-unsigned-build:
    name: iOS Build (Unsigned for 3uTools)
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Clean and Get Packages
        script: |
          flutter clean
          flutter pub get

      - name: Configure Podfile (Maintain iOS Data/Permissions)
        script: |
          # This step restores your specific iOS settings (Permissions, iOS 15.5)
          # preventing "missing permission" crashes later.
          cat <<EOF > ios/Podfile
          platform :ios, '15.5'
          ENV['COCOAPODS_DISABLE_STATS'] = 'true'

          project 'Runner', {
            'Debug' => :debug,
            'Profile' => :release,
            'Release' => :release,
          }

          def flutter_root
            generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
            unless File.exist?(generated_xcode_build_settings_path)
              raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
            end

            File.foreach(generated_xcode_build_settings_path) do |line|
              matches = line.match(/FLUTTER_ROOT\=(.*)/)
              return matches[1].strip if matches
            end
            raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
          end

          require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

          flutter_ios_podfile_setup

          target 'Runner' do
            use_frameworks!
            use_modular_headers!

            flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
          end

          post_install do |installer|
            installer.pods_project.targets.each do |target|
              flutter_additional_ios_build_settings(target)
              target.build_configurations.each do |config|
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.5'
                config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
                  '\$(inherited)',
                  'PERMISSION_CAMERA=1',
                  'PERMISSION_MICROPHONE=1',
                  'PERMISSION_PHOTOS=1',
                  'PERMISSION_APP_TRACKING_TRANSPARENCY=1',
                  'PERMISSION_BLUETOOTH=1',
                ]
              end
            end
          end
          EOF

      - name: Patch AppDelegate (Fix PrintService Crash)
        script: |
          # Finds lines with "PrintService" in AppDelegate.swift and comments them out
          # This prevents the "Cannot find PrintService in scope" build error
          sed -i '' 's/.*PrintService.*/\/\/ &/' ios/Runner/AppDelegate.swift

      - name: Install CocoaPods (Clean Install)
        script: |
          cd ios
          rm -rf Pods
          rm -rf Podfile.lock
          pod install --repo-update
          cd ..

      - name: Build iOS Release (No Code Signing)
        script: |
          flutter build ios --release --no-codesign --build-number=$BUILD_NUMBER

      - name: Create IPA from .app
        script: |
          cd build/ios/iphoneos
          
          # Clean up previous artifacts
          rm -rf Payload
          rm -rf *.ipa
          
          # Create Payload structure
          mkdir Payload
          cp -r Runner.app Payload/
          
          # Zip into IPA
          zip -r MyInvois_e-Pos.ipa Payload

    artifacts:
      - build/ios/iphoneos/*.ipa