workflows:
  ios-unsigned-build:
    name: iOS Build (Unsigned for 3uTools)
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Clean and Get Packages
        script: |
          flutter clean
          flutter pub get

      - name: Install CocoaPods (Deep Clean & Fix)
        script: |
          cd ios
          
          # 1. Force remove existing Pod artifacts to prevent caching issues
          rm -rf Pods
          rm -rf Podfile.lock
          
          # 2. Update the Master Specs Repo explicitly
          # This is the specific fix for the "out-of-date" error you saw
          pod repo update
          
          # 3. Install pods using the fresh specs
          pod install
          cd ..

      - name: Build iOS Release (No Code Signing)
        script: |
          flutter build ios --release --no-codesign --build-number=$BUILD_NUMBER

      - name: Create IPA from .app
        script: |
          cd build/ios/iphoneos
          
          # 1. Clean up any previous artifacts
          rm -rf Payload *.ipa
          
          # 2. Create Payload structure required by iOS
          mkdir Payload
          
          # 3. Copy the built app into the Payload folder
          cp -r Runner.app Payload/
          
          # 4. Zip it into an IPA file
          zip -r "MyInvois_e-Pos_Printer.ipa" Payload

    artifacts:
      - build/ios/iphoneos/*.ipa