workflows:
  ios-unsigned-build:
    name: iOS Build (Unsigned for 3uTools)
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Clean and Get Packages
        script: |
          flutter clean
          flutter pub get

      - name: Install Pods & Build iOS Release
        script: |
          # 1. Enter iOS directory
          cd ios

          # 2. Clean existing artifacts to ensure a fresh start
          rm -rf Pods
          rm -f Podfile.lock

          # 3. Install Pods with FORCED repo update
          # The flag --repo-update is critical here. It forces CocoaPods to 
          # fetch the missing specs (like share_handler_ios_models) immediately.
          pod install --repo-update

          # 4. Return to root
          cd ..

          # 5. Build the .app bundle without signing
          # Since we just ran pod install successfully above, Flutter will 
          # detect the existing Pods and skip the failing internal pod install.
          flutter build ios --release --no-codesign --build-number=$BUILD_NUMBER

      - name: Create IPA from .app
        script: |
          cd build/ios/iphoneos
          
          # 1. Clean up previous artifacts
          rm -rf Payload *.ipa
          
          # 2. Create the Payload folder structure required by Apple
          mkdir Payload
          
          # 3. Copy the Runner.app into Payload
          cp -r Runner.app Payload/
          
          # 4. Zip the Payload folder into an .ipa file
          zip -r "MyInvois_e-Pos_Printer.ipa" Payload

    artifacts:
      - build/ios/iphoneos/*.ipa