workflows:
  ios-unsigned-build:
    name: iOS Build (Unsigned for 3uTools)
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Clean and Get Packages
        script: |
          flutter clean
          flutter pub get

      - name: Install CocoaPods (Clean Install)
        script: |
          # Go to iOS folder
          cd ios
          
          # Remove existing Pods to force a refresh (Critical after Podfile changes)
          rm -rf Pods
          rm -rf Podfile.lock
          
          # Install fresh pods
          pod install --repo-update
          cd ..

      - name: Build iOS Release (No Code Signing)
        script: |
          # Build the .app bundle without signing
          # Note: We use --no-codesign to generate a raw .app bundle
          flutter build ios --release --no-codesign --build-number=$BUILD_NUMBER

      - name: Create IPA from .app
        script: |
          # Navigate to the build output directory
          cd build/ios/iphoneos
          
          # 1. Clean up previous artifacts
          rm -rf Payload
          rm -rf *.ipa
          
          # 2. Create the Payload folder structure required by Apple
          mkdir Payload
          
          # 3. Copy the Runner.app into Payload
          cp -r Runner.app Payload/
          
          # 4. Zip the Payload folder into an .ipa file
          # We name it clearly so you know it is unsigned
          zip -r epos_plugin.ipa Payload

    artifacts:
      - build/ios/iphoneos/*.ipa