workflows:
  ios-unsigned-build:
    name: iOS Build (Unsigned for 3uTools)
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Clean and Get Packages
        script: |
          flutter clean
          flutter pub get

      - name: Install CocoaPods (Clean Install)
        script: |
          cd ios
          
          # Remove existing Pods to ensure no conflicts
          rm -rf Pods
          rm -rf Podfile.lock
          
          # Install pods and update the repo in one go (The Fix)
          pod install --repo-update
          cd ..

      - name: Build iOS Release (No Code Signing)
        script: |
          flutter build ios --release --no-codesign --build-number=$BUILD_NUMBER

      - name: Create IPA from .app
        script: |
          cd build/ios/iphoneos
          
          # 1. Clean up
          rm -rf Payload *.ipa
          
          # 2. Create Payload structure
          mkdir Payload
          
          # 3. Copy Runner
          cp -r Runner.app Payload/
          
          # 4. Zip it (I restored your original filename here, change it back if you prefer 'epos_pilot')
          zip -r "MyInvois_e-Pos_Printer.ipa" Payload

    artifacts:
      - build/ios/iphoneos/*.ipa