workflows:
  ios-unsigned-fix:
    name: iOS Unsigned (Auto-Repair)
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    
    scripts:
      - name: Repair Corrupted Xcode Project
        script: |
          # 1. Delete the corrupted project settings file from the repo
          echo "Deleting damaged Runner.xcodeproj..."
          rm -rf ios/Runner.xcodeproj
          
          # 2. Force Flutter to regenerate the ios project structure
          # This creates a fresh, working project file while keeping your code/Info.plist
          echo "Regenerating iOS project..."
          flutter create . --platforms ios

      - name: Get Flutter packages
        script: |
          # 3. Download Dart dependencies
          flutter pub get

      - name: Install Pods
        script: |
          # 4. Install iOS dependencies (Standard method)
          # We use a clean install to avoid caching issues
          cd ios
          rm -rf Pods
          rm -f Podfile.lock
          pod install
          cd ..

      - name: Build iOS App (No Codesign)
        script: |
          # 5. Build the Release version, skipping code signing
          flutter build ios --release --no-codesign

      - name: Package as IPA
        script: |
          # 6. Navigate to the build output
          cd build/ios/iphoneos
          
          # 7. Create the IPA folder structure (Payload/Runner.app)
          mkdir Payload
          mv Runner.app Payload/
          
          # 8. Zip it into an IPA (using -y to preserve symlinks)
          zip -r -y app_unsigned.ipa Payload/
          
          # 9. Export artifact
          mv app_unsigned.ipa $CM_EXPORT_DIR/runner_unsigned.ipa

    artifacts:
      - $CM_EXPORT_DIR/*.ipa