workflows:
  ios-unsigned-fix:
    name: iOS Unsigned (Auto-Repair)
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    
    scripts:
      - name: Repair Corrupted Xcode Project
        script: |
          # 1. Delete the corrupted project settings file from the repo
          echo "Deleting damaged Runner.xcodeproj..."
          rm -rf ios/Runner.xcodeproj
          
          # 2. Force Flutter to regenerate the ios project structure
          # This creates a fresh, working project file while keeping your code/Info.plist
          echo "Regenerating iOS project..."
          flutter create . --platforms ios

      - name: Get Flutter packages
        script: |
          # 3. Download Dart dependencies
          flutter pub get

      - name: Configure Podfile with Permissions
        script: |
          # 4. Overwrite ios/Podfile with the correct configuration
          # This ensures we have the Permission Macros and iOS 13 targets
          cat <<EOF > ios/Podfile
          platform :ios, '13.0'
          ENV['COCOAPODS_DISABLE_STATS'] = 'true'

          project 'Runner', {
            'Debug' => :debug,
            'Profile' => :release,
            'Release' => :release,
          }

          def flutter_root
            generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
            unless File.exist?(generated_xcode_build_settings_path)
              raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
            end

            File.foreach(generated_xcode_build_settings_path) do |line|
              matches = line.match(/FLUTTER_ROOT\=(.*)/)
              return matches[1].strip if matches
            end
            raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
          end

          require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

          flutter_ios_podfile_setup

          target 'Runner' do
            use_frameworks!
            use_modular_headers!

            flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

            target 'RunnerTests' do
              inherit! :search_paths
            end
          end

          post_install do |installer|
            installer.pods_project.targets.each do |target|
              flutter_additional_ios_build_settings(target)

              target.build_configurations.each do |config|
                # Force iOS 13.0 deployment target
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'

                # Permission Macros
                config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
                  '\$(inherited)',
                  'PERMISSION_CAMERA=1',
                  'PERMISSION_MICROPHONE=1',
                  'PERMISSION_PHOTOS=1',
                  'PERMISSION_APP_TRACKING_TRANSPARENCY=1',
                  'PERMISSION_BLUETOOTH=1',
                ]
              end
            end
          end
          EOF

      - name: Install Pods
        script: |
          # 5. Install iOS dependencies using the custom Podfile
          cd ios
          rm -rf Pods
          rm -f Podfile.lock
          pod install
          cd ..

      - name: Build iOS App (No Codesign)
        script: |
          # 6. Build the Release version, skipping code signing
          flutter build ios --release --no-codesign

      - name: Package as IPA
        script: |
          # 7. Navigate to the build output
          cd build/ios/iphoneos
          
          # 8. Create the IPA folder structure (Payload/Runner.app)
          mkdir Payload
          mv Runner.app Payload/
          
          # 9. Zip it into an IPA (using -y to preserve symlinks)
          zip -r -y app_unsigned.ipa Payload/
          
          # 10. Export artifact
          mv app_unsigned.ipa $CM_EXPORT_DIR/runner_unsigned.ipa

    artifacts:
      - $CM_EXPORT_DIR/*.ipa