workflows:
  ios-unsigned-fix:
    name: iOS Unsigned (Auto-Repair Project)
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Repair Corrupted Xcode Project
        script: |
          # 1. Delete the corrupted project settings file
          echo "Deleting damaged Runner.xcodeproj..."
          rm -rf ios/Runner.xcodeproj
          
          # 2. Force Flutter to regenerate the ios project structure
          # This keeps your code (AppDelegate, Info.plist) but creates a fresh, working .xcodeproj
          echo "Regenerating iOS project..."
          flutter create . --platforms ios

      - name: Install CocoaPods
        script: |
          # 3. Re-install pods now that the project file is fixed
          find . -name "Podfile" -execdir pod install \;

      - name: Build iOS App (No Codesign)
        script: |
          # 4. Build the Release version, skipping code signing
          flutter build ios --release --no-codesign

      - name: Package as IPA
        script: |
          # 5. Navigate to the build output
          cd build/ios/iphoneos
          
          # 6. Create the IPA folder structure (Payload/Runner.app)
          mkdir Payload
          mv Runner.app Payload/
          
          # 7. Zip it into an IPA (using -y to preserve symlinks)
          zip -r -y app_unsigned.ipa Payload/
          
          # 8. Export artifact
          mv app_unsigned.ipa $CM_EXPORT_DIR/runner_unsigned.ipa

    artifacts:
      - $CM_EXPORT_DIR/*.ipa