workflows:
  ios-unsigned-build:
    name: iOS Build (Unsigned for 3uTools)
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

    scripts:
      - name: Clean and Get Flutter Packages
        script: |
          flutter clean
          flutter pub get

      - name: Install CocoaPods (Fix share_handler_ios_models)
        script: |
          cd ios

          # Fully reset CocoaPods state
          pod deintegrate || true
          rm -rf Pods
          rm -f Podfile.lock

          # Install pods AND update repo (critical fix)
          pod install --repo-update

          cd ..

      - name: Build iOS Release (No Code Signing)
        script: |
          flutter build ios \
            --release \
            --no-codesign \
            --build-number=$BUILD_NUMBER

      - name: Create IPA from .app
        script: |
          cd build/ios/iphoneos

          rm -rf Payload *.ipa
          mkdir Payload
          cp -r Runner.app Payload/

          zip -r "MyInvois_e-Pos_Printer.ipa" Payload

    artifacts:
      - build/ios/iphoneos/*.ipa
