workflows:
  ios-unsigned-build:
    name: iOS Build (Unsigned for 3uTools)
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Clean and Get Packages
        script: |
          flutter clean
          flutter pub get

      - name: Fix Podfile & Build
        script: |
          cd ios

          # 1. Force the Podfile to use the official CDN
          # This inserts "source 'https://cdn.cocoapods.org/'" at the very top of your Podfile
          echo "source 'https://cdn.cocoapods.org/'" | cat - Podfile > Podfile.tmp && mv Podfile.tmp Podfile

          # 2. Clean existing Pods and Lockfile
          rm -rf Pods
          rm -f Podfile.lock

          # 3. Nuclear Reset of CocoaPods Trunk
          # We remove the repo to clear corrupted cache, then install adds it back fresh.
          pod repo remove trunk || true
          
          # 4. Install Pods (This will re-fetch the specs fresh)
          pod install

          # 5. Build
          cd ..
          flutter build ios --release --no-codesign --build-number=$BUILD_NUMBER

      - name: Create IPA from .app
        script: |
          cd build/ios/iphoneos
          
          # 1. Clean up previous artifacts
          rm -rf Payload *.ipa
          
          # 2. Create the Payload folder structure required by Apple
          mkdir Payload
          
          # 3. Copy the Runner.app into Payload
          cp -r Runner.app Payload/
          
          # 4. Zip the Payload folder into an .ipa file
          zip -r "MyInvois_e-Pos_Printer.ipa" Payload

    artifacts:
      - build/ios/iphoneos/*.ipa